version: '3.7'
services:
  products-service:
    image: co.edu.javeriana.pica.services/products-service:latest
    container_name: products-service
    hostname: products-service
    restart: always
    networks:
      - ntw_cloud
      - ntw_backend
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DCONFIG_SERVER=http://config-server:9090
        -DEUREKA_SERVER=http://discovery-server:9091/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    ports:
      - 8001

networks:
  ntw_cloud:
    external: true
  ntw_backend:
    external: true